import pyautogui as pg
import time

pg.PAUSE = 0.1

time.sleep(2)

pg.typewrite("Hexabytes")
pg.press("tab")
pg.typewrite("U-0163")
pg.press("tab", 8)
pg.press("space")
pg.typewrite("imagetopdf.pdf")
pg.press("enter")
time.sleep(1)
pg.press("tab")

pg.typewrite("Aaditya")
pg.press("tab")
pg.press("tab")
pg.typewrite("Verma")
pg.press("tab")
pg.typewrite("aaditya16csu001@ncuindia.edu")
pg.press("tab")
pg.typewrite("9582906389")
pg.press("tab")
pg.typewrite("M")
pg.press("tab")

pg.typewrite("Sweta")
pg.press("tab")
pg.typewrite("Sahu")
pg.press("tab")
pg.typewrite("sweta16csu382@ncuindia.edu")
pg.press("tab")
pg.typewrite("9540741312")
pg.press("tab")
pg.typewrite("F")
pg.press("tab")

pg.typewrite("Medha")
pg.press("tab")
pg.typewrite("Gulati")
pg.press("tab")
pg.typewrite("medhagulati6@gmail.com")
pg.press("tab")
pg.typewrite("9654579287")
pg.press("tab")
pg.typewrite("F")
pg.press("tab")

pg.typewrite("Ananda")
pg.press("tab")
pg.typewrite("Sreenidhi")
pg.press("tab")
pg.typewrite("anandasreenidhi@gmail.com")
pg.press("tab")
pg.typewrite("7011429917")
pg.press("tab")
pg.typewrite("F")
pg.press("tab")

pg.typewrite("Sambhav")
pg.press("tab")
pg.typewrite("Dalal")
pg.press("tab")
pg.typewrite("sambhavdalal@gmail.com")
pg.press("tab")
pg.typewrite("8708824621")
pg.press("tab")
pg.typewrite("M")
pg.press("tab")

pg.typewrite("Kashish")
pg.press("tab")
pg.typewrite("Verma")
pg.press("tab")
pg.typewrite("kashishverma22101997@gmail.com")
pg.press("tab")
pg.typewrite("9953568731")
pg.press("tab")
pg.typewrite("M")
pg.press("tab")

# pg.press("space")


